---
  - name: Register with Red Hat Subscription Manager
    command: subscription-manager register --username={{ rhn_user }} --password={{ rhn_pass }} --force
  - name: Attach subscription
    command: subscription-manager attach --pool="{{ rhn_pool }}"
  - name: Disable all repos
    command: subscription-manager repos --disable "*"
  - name: Enable necessary repos
    command: subscription-manager repos --enable="rhel-7-server-rpms"     --enable="rhel-7-server-extras-rpms"     --enable="rhel-7-server-ose-3.6-rpms"     --enable="rhel-7-fast-datapath-rpms"
  - name: Install necessary packages
    yum:  
      name: '{{ item }}'
      state: present
    with_items: 
    - wget 
    - git 
    - net-tools 
    - bind-utils 
    - iptables-services 
    - bridge-utils 
    - bash-completion 
    - kexec-tools 
    - sos 
    - psacct
    - atomic-openshift-utils
    - docker-1.12.6
    - ipa-client
  - name: configure IPA client
    command: ipa-client-install --server='{{ ipa_server }}' --domain='{{ domain }}' --hostname='{{ ansible_hostname }}'.'{{ domain }}' --principal='{{ ipa_user }}' --password='{{ ipa_password }}' --enable-dns-updates --unattended
  - name: configure docker storage
    template:
      src: docker-storage-setup.j2
      dest: /etc/sysconfig/docker-storage-setup
      owner: root
      group: root
      mode: 0644
  - name: run docker storage setup
    command: docker-storage-setup
  - name: start and enable Docker
    service:
      name: docker
      state: started
      enabled: true
  - name: Copy hoststemplate file
    template:
      src: hosts.j2
      dest: /etc/ansible/hosts
      owner: root
      group: root
      mode: 0644
    when: "'master' in group_names"
  - name: create ssh key on root account
    shell: 'ssh-keygen -b 2048 -t rsa -f /root/.ssh/id_rsa -q -N ""'
    when: "'master' in group_names"
# Placholder = "cat /path/to/id_rsa.pub >> /root/.ssh/authorized_keys" 
# Need to save stdout of cat id_rsa.pub to a var, then write that to authorized keys on all hosts - will implement/test later.  Also need to add to scaleup
  - name: copy key to localhosts
    shell: 'sshpass -p {{ ssh_pass }} ssh-copy-id root@localhost'
  - name: Install OpenShift unattended
    command: ansible-playbook  -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
    when: "'master' in group_names"
    ignore_errors: True
