---
- hosts: localhost
  connection: local
#  vars_files:
#    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "https://rhevm.rdu.salab.redhat.com/ovirt-engine/api"
      username: "admin@internal"
      password: "Redhat1!"
      insecure: "true"

  - name: Get VMs from datacenter X
    ovirt_vms_facts:
      fetch_nested: true
      pattern: name=ocp-master-ldo-378c and datacenter=RDU-RHS
      auth: "{{ovirt_auth }}"
  - debug:
      msg: "{{ ovirt_vms }}"
      #msg: "{{ ovirt_vms | map(attribute='fqdn') | list }}"
  
  - set_fact:
       masterip: "{{ ovirt_vms | map(attribute='fqdn') | list }}"
  
  - debug:
      var:  masterip
    


  - name: List vms
    ovirt_vms_facts:
      fetch_nested: true
      nested_attributes:
        - description
      auth: "{{ ovirt_auth }}"

  - name: set vms
    set_fact:
       vm: "{{ item.name }}: {{ item.snapshots | map(attribute='description') | join(',') }}"
    with_items: "{{ ovirt_vms }}"
    loop_control:
      label: "{{ item.name }}"
    register: all_vms

  - name: make a list
    set_fact: vms="{{ all_vms.results | map(attribute='ansible_facts.vm') | list }}"

  - name: Print vms
    debug:
      var: vms
