---
- hosts: localhost
  connection: local
  gather_facts: no
  user: root
  vars:
    type: master
    master: true
    node: true
    ipaddr: "{{ master1 }}"
  roles:
    - {role: 'ocp-rhv'}
    - { role: manageiq, when: manageiq is defined }

- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
    ipaddr: "{{ node1 }}"
  roles:
    - {role: 'ocp-rhv'}
    - { role: manageiq, when: manageiq is defined }
    

- hosts: master:node
  remote_user: root
  roles:
    - {role: 'ocp-quick'}
