---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - '../main.yml'
  vars:
    type: master
    master: true
    node: true
  roles:
    - {role: 'ocp-vmware'}

- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'ocp-vmware'}

- hosts: all
  remote_user: root
  vars_files:
    - '../main.yml'
  roles:
    - {role: 'ocp-quick'}
