---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars:
    type: node
    master: false
    node: true
#  vars_files:
#    - '../main.yml'
  roles:
    - {role: 'ocp-osp'}
  tasks: 
    - name: add master server to inventory
      add_host:
        hostname: "{{ master1 }}"
        ansible_ssh_user: "{{ ssh_user }}"
        groupname: master

- hosts: !localhost
  remote_user: root
  become: true

#  vars_files:
#    - '../main.yml'
  tasks:
    - name: add newnodes line
      lineinfile:
        dest: /etc/ansible/hosts
        state: present
        insertafter: '^nodes'
        line: 'new_nodes'

    - name: add newnodes block
      blockinfile:
        insertafter: EOF
        path: /etc/ansible/hosts
        content: |
          [new_nodes]
          {{ hostvars[groups['node'][0]]['ansible_fqdn'] }}
- hosts: all
  remote_user: cloud-user
  become: true
#  vars_files:
#    - '../main.yml'
  roles:
    - {role: 'ocp-scaleup'}
