---
  - name: Register with Red Hat Subscription Manager
    command: subscription-manager register --username={{ rhn_user }} --password={{ rhn_pass }} --force
  - name: Attach subscription
    command: subscription-manager attach --pool="{{ rhn_pool }}"
  - name: Disable all repos
    command: subscription-manager repos --disable "*"
  - name: Enable necessary repos
    command: subscription-manager repos --enable="rhel-7-server-rpms"     --enable="rhel-7-server-extras-rpms"     --enable="rhel-7-server-ose-3.6-rpms"     --enable="rhel-7-fast-datapath-rpms"
  - name: Install necessary packages
    yum:  
      name: '{{ item }}'
      state: present
    with_items: 
    - wget 
    - git 
    - net-tools 
    - bind-utils 
    - iptables-services 
    - bridge-utils 
    - bash-completion 
    - kexec-tools 
    - sos 
    - psacct
    - atomic-openshift-utils
    - docker-1.12.6
  - name: configure docker storage
    template:
      src: docker-storage-setup.j2
      dest: /etc/sysconfig/docker-storage-setup
      owner: root
      group: root
      mode: 0644
  - name: start and enable Docker
    service:
      name: docker
      state: started
      enabled: true
  - name: Copy installer config
    copy:
      src: files/installer.cfg.yml
      dest: /root/installer.cfg.yml
    when: "'master' in group_names"
  - name: Install OpenShift unattended
    command: atomic-openshift-installer -u -c ~/installer.cfg.yml install
    when: "'master' in group_names"
    ignore_errors: True
